USE [master]
GO
/****** Object:  Database [CakeShopDb]    Script Date: 10/2/2022 1:12:53 AM ******/
CREATE DATABASE [CakeShopDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CakeShopDb', FILENAME = N'E:\SQLData\MSSQL15.MSSQLSERVER\MSSQL\DATA\CakeShopDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CakeShopDb_log', FILENAME = N'E:\SQLData\MSSQL15.MSSQLSERVER\MSSQL\DATA\CakeShopDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [CakeShopDb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CakeShopDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CakeShopDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CakeShopDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CakeShopDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CakeShopDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CakeShopDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [CakeShopDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CakeShopDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CakeShopDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CakeShopDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CakeShopDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CakeShopDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CakeShopDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CakeShopDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CakeShopDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CakeShopDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CakeShopDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CakeShopDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CakeShopDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CakeShopDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CakeShopDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CakeShopDb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [CakeShopDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CakeShopDb] SET RECOVERY FULL 
GO
ALTER DATABASE [CakeShopDb] SET  MULTI_USER 
GO
ALTER DATABASE [CakeShopDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CakeShopDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CakeShopDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CakeShopDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CakeShopDb] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'CakeShopDb', N'ON'
GO
ALTER DATABASE [CakeShopDb] SET QUERY_STORE = OFF
GO
USE [CakeShopDb]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 10/2/2022 1:12:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CakeShapes]    Script Date: 10/2/2022 1:12:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CakeShapes](
	[Id] [uniqueidentifier] NOT NULL,
	[ShapeName] [nvarchar](max) NOT NULL,
	[ShapePrice] [real] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedBy] [int] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_CakeShapes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Toppings]    Script Date: 10/2/2022 1:12:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Toppings](
	[Id] [uniqueidentifier] NOT NULL,
	[ToppingName] [nvarchar](max) NOT NULL,
	[InitialQuantity] [int] NOT NULL,
	[ToppingPrice] [decimal](18, 2) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedBy] [int] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Toppings] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserForms]    Script Date: 10/2/2022 1:12:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserForms](
	[UserID] [uniqueidentifier] NOT NULL,
	[UserName] [nvarchar](max) NOT NULL,
	[PasswordHash] [varbinary](max) NOT NULL,
	[PasswordSalt] [varbinary](max) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedBy] [int] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_UserForms] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20221001004424_initial', N'6.0.9')
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20221001160946_new2', N'6.0.9')
GO
INSERT [dbo].[CakeShapes] ([Id], [ShapeName], [ShapePrice], [IsActive], [CreatedBy], [CreatedDate]) VALUES (N'983136a6-9402-4a5e-9aa8-7babb93dd8a4', N'Square', 5, 1, 1, CAST(N'2022-10-01T00:46:48.0390000' AS DateTime2))
GO
INSERT [dbo].[CakeShapes] ([Id], [ShapeName], [ShapePrice], [IsActive], [CreatedBy], [CreatedDate]) VALUES (N'983136a6-9402-4a5e-9aa8-7babb93dd8a8', N'Round', 7, 1, 1, CAST(N'2022-10-01T00:46:48.0390000' AS DateTime2))
GO
INSERT [dbo].[Toppings] ([Id], [ToppingName], [InitialQuantity], [ToppingPrice], [IsActive], [CreatedBy], [CreatedDate]) VALUES (N'2dd6f9b9-96cd-45b6-8989-1fc2cf72bc53', N'Fresh Strawberries', 4, CAST(2.00 AS Decimal(18, 2)), 1, 1, CAST(N'2022-10-01T03:08:48.9710000' AS DateTime2))
GO
INSERT [dbo].[Toppings] ([Id], [ToppingName], [InitialQuantity], [ToppingPrice], [IsActive], [CreatedBy], [CreatedDate]) VALUES (N'81065227-d225-4965-ac60-4cc59be39527', N'Dipped Strawberries Dark Chocolate', 4, CAST(2.50 AS Decimal(18, 2)), 1, 1, CAST(N'2022-10-01T03:08:48.9710000' AS DateTime2))
GO
INSERT [dbo].[Toppings] ([Id], [ToppingName], [InitialQuantity], [ToppingPrice], [IsActive], [CreatedBy], [CreatedDate]) VALUES (N'13c33122-56fc-4a37-8408-b0cb54360788', N'Dipped Strawberries White Chocolate', 4, CAST(3.00 AS Decimal(18, 2)), 1, 1, CAST(N'2022-10-01T03:08:48.9710000' AS DateTime2))
GO
INSERT [dbo].[UserForms] ([UserID], [UserName], [PasswordHash], [PasswordSalt], [IsActive], [CreatedBy], [CreatedDate]) VALUES (N'dddb2355-e5e6-4bc0-ac9f-61be9ea6d0d1', N'User1', 0x26E76F91D30113FAECF50E58AE53C0AB149F8D916F39720C2FFA3501F459A58288047C6C2793C4C0784617EE5232972C3BD904459CBE51CB8F93BE0F39A9319A, 0x6C86EBCD7693E194A7D8B8CF0618D53E247DF3C3C7A36003A92ED25744EC9C86F24128EB17AE01B04C1B4C7D65159F53C11B532FF2B6B74A19A2CAA74DA6C41B85AFB7C07360BF931FB7EAE04BE59C191E71296EE1584013B437E3C532B3167E76CD514D4DED56E8A5F9CFD4979C99691F1CEC853FB0BE04F72E9B5D6FA89346, 1, 1, CAST(N'0001-01-01T00:00:00.0000000' AS DateTime2))
GO
USE [master]
GO
ALTER DATABASE [CakeShopDb] SET  READ_WRITE 
GO
